export const getSpecialists = async () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        psychologists: [
          {
            id: 1,
            selection: 'best-match',
            avatar: '/assets/mockPhotos/Tetiana.jpg',
            name: 'Тетяна Дума',
            verified: true,
            experience: '1',
            specialties: ['Психотерапевт', 'Сексолог'],
            records: '9',
            watching: '18',
            cost: '20',
            sessions: '228',
            likes: '8',
          },
          {
            id: 2,
            selection: 'recommended',
            avatar: '/assets/mockPhotos/Tetiana.jpg',
            name: 'Тетяна Дума',
            verified: true,
            experience: '1',
            specialties: ['Психотерапевт', 'Сексолог'],
            records: '9',
            watching: '18',
            cost: '20',
            sessions: '228',
            likes: '8',
          },
          {
            id: 3,
            selection: '',
            avatar: '/assets/mockPhotos/Tetiana.jpg',
            name: 'Тетяна Дума',
            verified: true,
            experience: '1',
            specialties: ['Психотерапевт', 'Сексолог'],
            records: '9',
            watching: '18',
            cost: '20',
            sessions: '228',
            likes: '8',
          },
          {
            id: 4,
            selection: '',
            avatar: '/assets/mockPhotos/Tetiana.jpg',
            name: 'Тетяна Дума',
            verified: true,
            experience: '1',
            specialties: ['Психотерапевт', 'Сексолог'],
            records: '9',
            watching: '18',
            cost: '20',
            sessions: '228',
            likes: '8',
          },
        ],
        esoterics: [
          {
            id: 5,
            selection: 'recommended',
            avatar: '/assets/mockPhotos/Tetiana.jpg',
            name: 'Тетяна Дума',
            verified: true,
            experience: '3',
            specialties: ['Космоенергет', 'Регресолог'],
            records: '3',
            watching: '12',
            cost: '50',
            sessions: '178',
            likes: '7',
          },
          {
            id: 6,
            selection: '',
            avatar: '/assets/mockPhotos/Tetiana.jpg',
            name: 'Тетяна Дума',
            verified: true,
            experience: '1',
            specialties: ['Космоенергет', 'Парапсихолог'],
            records: '9',
            watching: '18',
            cost: '20',
            sessions: '228',
            likes: '8',
          },
          {
            id: 7,
            selection: '',
            avatar: '/assets/mockPhotos/Tetiana.jpg',
            name: 'Тетяна Дума',
            verified: true,
            experience: '1',
            specialties: ['Космоенергет', 'Парапсихолог'],
            records: '9',
            watching: '18',
            cost: '20',
            sessions: '228',
            likes: '8',
          },
        ],
      });
    }, 500); // задержку сделал типа с сервака, потом удалить
  });
};
